def v_bitBucketUrl = 'https://github.com/shaktipp/dmpRepo.git'
def v_gitHubUrl = 'https://github.com/shaktipp/cucumber.git'
def v_bitbucketBranchName = 'develop'
def v_pomFilePath = 'MathCucumberApp/pom.xml'
def v_imageName = 'shaktipp/mathcucumber-image'
def v_dockerfilePath = 'MathCucumberApp/dmp/docker'
def v_successNotification = 'shaktiprasadapanda@fico.com';
def v_failNotification = 'shaktiprasadapanda@fico.com,shaktipp@gmail.com';


///////////////////////////////////////////////PLEASE DONT EDIT/DELETE BELOW CODE//////////////////////////////////////////////////////
pipeline {
	environment {
		DOCKER = credentials('GitHub_SPP')
	}

	agent any

	tools {
		maven 'Maven352'
	}

	stages {
		
		stage('Checkout') {
			steps {
				//git credentialsId: 'BitBucket', url: v_bitBucketUrl, branch: v_bitbucketBranchName
				git v_gitHubUrl
			}
		}
		stage('Build') {
			steps {
				sh "mvn -f ${v_pomFilePath} clean compile"
			}
		}
		stage('Test') {
			steps {
				sh "mvn -f ${v_pomFilePath} test"
				junit '**/target/surefire-reports/TEST-*.xml'
				archive 'target/*.jar'
			}
		}
		
		stage('Package and Checkmarx') {
			steps {
				sh "mvn -f ${v_pomFilePath} package"
				step([$class: 'CxScanBuilder', comment: 'Checkmark Static Code Analyss', credentialsId: '', excludeFolders: '', excludeOpenSourceFolders: '', exclusionsSetting: 'job', failBuildOnNewResults: false, failBuildOnNewSeverity: 'HIGH', filterPattern: 	'''!**/_cvs/**/*, !**/.svn/**/*,   !**/.hg/**/*,   !**/.git/**/*,  !**/.bzr/**/*, !**/bin/**/*,
				!**/obj/**/*,  !**/backup/**/*, !**/.idea/**/*, !**/*.DS_Store, !**/*.ipr,     !**/*.iws,
				!**/*.bak,     !**/*.tmp,       !**/*.aac,      !**/*.aif,      !**/*.iff,     !**/*.m3u, !**/*.mid, !**/*.mp3,
				!**/*.mpa,     !**/*.ra,        !**/*.wav,      !**/*.wma,      !**/*.3g2,     !**/*.3gp, !**/*.asf, !**/*.asx,
				!**/*.avi,     !**/*.flv,       !**/*.mov,      !**/*.mp4,      !**/*.mpg,     !**/*.rm,  !**/*.swf, !**/*.vob,
				!**/*.wmv,     !**/*.bmp,       !**/*.gif,      !**/*.jpg,      !**/*.png,     !**/*.psd, !**/*.tif, !**/*.swf,
				 !**/*.rar,      !**/*.exe,      !**/*.dll,     !**/*.pdb, !**/*.7z,  !**/*.gz,
				!**/*.tar.gz,  !**/*.tar,       !**/*.gz,       !**/*.ahtm,     !**/*.ahtml,   !**/*.fhtml, !**/*.hdm,
				!**/*.hdml,    !**/*.hsql,      !**/*.ht,       !**/*.hta,      !**/*.htc,     !**/*.htd, 
				!**/*.htmls,   !**/*.ihtml,     !**/*.mht,      !**/*.mhtm,     !**/*.mhtml,   !**/*.ssi, !**/*.stm,
				!**/*.stml,    !**/*.ttml,      !**/*.txn,      !**/*.xhtm,     !**/*.xhtml,   !**/*.class, !**/*.iml, !Checkmarx/Reports/*.*''', fullScanCycle: 10, groupId: '77817e0d-9700-46b5-aa44-16b474ba8416', includeOpenSourceFolders: '', jobStatusOnError: 'FAILURE', osaArchiveIncludePatterns: '*.zip, *.war, *.ear, *.tgz', password: '{AQAAABAAAAAQY8vsvHNzrPNGcSmj4kTwzkcy3DupBli81CPJO+Hv6zU=}', preset: '100000', projectName: 'MathAppUnitTesting', serverUrl: 'https://bnpappwis403.corp.fairisaac.com', sourceEncoding: '1', username: '', vulnerabilityThresholdResult: 'FAILURE'])

			}
		}
		stage('Sonar Scan') {
			steps {
				sh "mvn -f ${v_pomFilePath} sonar:sonar"
			}
		}
		
		stage('BDD') {
			steps {
				sh "mvn -f ${v_pomFilePath} install"
			}
		}

		stage('Build Image') {
			steps {				
				sh "docker build -t ${v_imageName} ${v_dockerfilePath}"
			}

		}
		stage('Push Image') {			
			steps {
				withDockerRegistry([credentialsId: 'docker-hub-credential', url: 'https://registry.hub.docker.com']) {
				  sh "docker push ${v_imageName}"
			    }
			}

		}
		
		stage('Create ZIP') {
			steps {				
				dir("./${v_dockerfilePath}/"){
					sh 'zip archeType.zip DMP-INF/*'
					sh 'mv archeType.zip ../../../'
				}//End of dir()	
			}
		}
		

	}//End of stages	
	post{
		success {
            mail to: "${v_successNotification}",
            subject: "Success Jenkins Build: ${currentBuild.fullDisplayName}",
            body: "Build is Successful, URL : ${env.BUILD_URL}"
        }
        unstable {
            mail to: "${v_failNotification}",
            subject: "Unstable Jenkins Build: ${currentBuild.fullDisplayName}",
            body: "Build is Unstable due to a few error, URL : ${env.BUILD_URL}"
        }
        failure {
            mail to: "${v_failNotification}",
            subject: "Failed Jenkins Build: ${currentBuild.fullDisplayName}",
            body: "Something is wrong with Pipeline Build , URL : ${env.BUILD_URL}"
        }
	
	}//End of post
		
}